const API = 'https://world.openfoodfacts.org';
const tools = [
  { name: 'search_products', description: 'Search food products by name, brand, or ingredient.', inputSchema: { type: 'object', properties: { query: { type: 'string', minLength: 2 }, page_size: { type: 'integer', minimum: 1, maximum: 20 } }, required: ['query'] } },
  { name: 'get_product', description: 'Get declared ingredients, allergens, and nutrition by product barcode.', inputSchema: { type: 'object', properties: { barcode: { type: 'string', pattern: '^[0-9]{6,24}$' } }, required: ['barcode'] } }
];
export function productUrl(path) { return new URL(path, API); }
async function getJson(url, fetcher = fetch) { const response = await fetcher(url, { headers: { accept: 'application/json', 'user-agent': 'public-interest-mcp/0.1 (open source)' }, signal: AbortSignal.timeout(15_000) }); if (!response.ok) throw new Error(`Upstream request failed (${response.status}).`); return response.json(); }
function present(product) { return { code: product.code, name: product.product_name, brands: product.brands, quantity: product.quantity, ingredients: product.ingredients_text, allergens: product.allergens, traces: product.traces, nutrition_grade: product.nutrition_grades, nutriments: product.nutriments, image_url: product.image_front_url }; }
export async function callTool(name, args = {}, fetcher = fetch) { if (name === 'search_products') { if (typeof args.query !== 'string' || args.query.trim().length < 2) throw new Error('query must contain at least two characters.'); const url = productUrl('/cgi/search.pl'); url.search = new URLSearchParams({ search_terms: args.query.trim(), search_simple: '1', action: 'process', json: '1', page_size: String(Math.min(Math.max(args.page_size || 10, 1), 20)), fields: 'code,product_name,brands,quantity,allergens,nutrition_grades,image_front_url' }); const data = await getJson(url, fetcher); return { count: data.count, products: (data.products || []).map(present) }; } if (name === 'get_product') { if (typeof args.barcode !== 'string' || !/^[0-9]{6,24}$/.test(args.barcode)) throw new Error('barcode must contain 6–24 digits.'); const data = await getJson(productUrl(`/api/v2/product/${args.barcode}.json?fields=code,product_name,brands,quantity,ingredients_text,allergens,traces,nutrition_grades,nutriments,image_front_url`), fetcher); if (data.status !== 1) throw new Error('Product not found.'); return present(data.product); } throw new Error(`Unknown tool: ${name}`); }
export function createServer(write = (line) => process.stdout.write(`${line}\n`)) { return async (message) => { const reply = (result) => message.id === undefined ? undefined : write(JSON.stringify({ jsonrpc: '2.0', id: message.id, result })); try { if (message.method === 'initialize') return reply({ protocolVersion: '2024-11-05', capabilities: { tools: {} }, serverInfo: { name: 'product-facts-mcp', version: '0.1.0' } }); if (message.method === 'tools/list') return reply({ tools }); if (message.method === 'tools/call') return reply({ content: [{ type: 'text', text: JSON.stringify(await callTool(message.params?.name, message.params?.arguments), null, 2) }] }); if (message.id !== undefined) write(JSON.stringify({ jsonrpc: '2.0', id: message.id, error: { code: -32601, message: 'Method not found' } })); } catch (error) { if (message.id !== undefined) write(JSON.stringify({ jsonrpc: '2.0', id: message.id, error: { code: -32000, message: error.message } })); } }; }
if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href) { const handle = createServer(); let buffer = ''; process.stdin.setEncoding('utf8').on('data', async (chunk) => { buffer += chunk; const lines = buffer.split('\n'); buffer = lines.pop(); for (const line of lines) if (line.trim()) { try { await handle(JSON.parse(line)); } catch { process.stderr.write('Invalid JSON-RPC message.\n'); } } }); }
