const tools = [
  { name: 'summarize_release_package', description: 'Summarize a public HTTPS Open Contracting release package.', inputSchema: { type: 'object', properties: { url: { type: 'string', format: 'uri' } }, required: ['url'] } },
  { name: 'find_awards', description: 'Find awards in a public HTTPS OCDS release package.', inputSchema: { type: 'object', properties: { url: { type: 'string', format: 'uri' }, supplier_query: { type: 'string' }, min_amount: { type: 'number', minimum: 0 } }, required: ['url'] } }
];
export function validatePublicUrl(value) { let url; try { url = new URL(value); } catch { throw new Error('url must be a valid HTTPS URL.'); } if (url.protocol !== 'https:' || ['localhost', '127.0.0.1', '::1'].includes(url.hostname) || url.hostname.endsWith('.local')) throw new Error('Only public HTTPS URLs are allowed.'); return url; }
async function getPackage(value, fetcher = fetch) { const url = validatePublicUrl(value); const response = await fetcher(url, { headers: { accept: 'application/json' }, redirect: 'error', signal: AbortSignal.timeout(20_000) }); if (!response.ok) throw new Error(`Upstream request failed (${response.status}).`); const body = await response.json(); if (!Array.isArray(body.releases)) throw new Error('The document is not an OCDS release package (missing releases array).'); return body; }
function awards(releases) { return releases.flatMap((release) => (release.awards || []).map((award) => ({ ocid: release.ocid, award_id: award.id, title: award.title, status: award.status, value: award.value, date: award.date, suppliers: (award.suppliers || []).map((s) => ({ id: s.id, name: s.name })) }))); }
export function summarize(data) { const all = awards(data.releases); const currencies = {}; for (const award of all) if (award.value?.currency && Number.isFinite(award.value.amount)) currencies[award.value.currency] = (currencies[award.value.currency] || 0) + award.value.amount; return { uri: data.uri, version: data.version, published_date: data.publishedDate, releases: data.releases.length, ocids: [...new Set(data.releases.map((r) => r.ocid).filter(Boolean))].length, buyers: [...new Set(data.releases.map((r) => r.buyer?.name).filter(Boolean))], awards: all.length, awarded_value_by_currency: currencies }; }
export async function callTool(name, args = {}, fetcher = fetch) { const data = await getPackage(args.url, fetcher); if (name === 'summarize_release_package') return summarize(data); if (name === 'find_awards') { if (args.supplier_query !== undefined && typeof args.supplier_query !== 'string') throw new Error('supplier_query must be text.'); if (args.min_amount !== undefined && (!Number.isFinite(args.min_amount) || args.min_amount < 0)) throw new Error('min_amount must be a non-negative number.'); const query = args.supplier_query?.trim().toLowerCase(); return { awards: awards(data.releases).filter((award) => (!query || award.suppliers.some((supplier) => supplier.name?.toLowerCase().includes(query))) && (args.min_amount === undefined || award.value?.amount >= args.min_amount)) }; } throw new Error(`Unknown tool: ${name}`); }
export function createServer(write = (line) => process.stdout.write(`${line}\n`)) { return async (message) => { const reply = (result) => message.id === undefined ? undefined : write(JSON.stringify({ jsonrpc: '2.0', id: message.id, result })); try { if (message.method === 'initialize') return reply({ protocolVersion: '2024-11-05', capabilities: { tools: {} }, serverInfo: { name: 'open-procurement-mcp', version: '0.1.0' } }); if (message.method === 'tools/list') return reply({ tools }); if (message.method === 'tools/call') return reply({ content: [{ type: 'text', text: JSON.stringify(await callTool(message.params?.name, message.params?.arguments), null, 2) }] }); if (message.id !== undefined) write(JSON.stringify({ jsonrpc: '2.0', id: message.id, error: { code: -32601, message: 'Method not found' } })); } catch (error) { if (message.id !== undefined) write(JSON.stringify({ jsonrpc: '2.0', id: message.id, error: { code: -32000, message: error.message } })); } }; }
if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href) { const handle = createServer(); let buffer = ''; process.stdin.setEncoding('utf8').on('data', async (chunk) => { buffer += chunk; const lines = buffer.split('\n'); buffer = lines.pop(); for (const line of lines) if (line.trim()) { try { await handle(JSON.parse(line)); } catch { process.stderr.write('Invalid JSON-RPC message.\n'); } } }); }
